version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ../elearning/Frontend/dist:/usr/share/nginx/html/elearning:ro
    depends_on:
      - express
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
